#!/bin/bash
# THIS FILE IS GENERATED BY tools/setup_anaconda.sh
if [ -z "${PS1:-}" ]; then
    PS1=__dummy__
fi
. /home4/md510/w2021/espnet_20210106_md/espnet/tools/venv/etc/profile.d/conda.sh && conda deactivate && conda activate espnet_20210106_home3_branch
